"""initial_schema

Revision ID: 74f1ce54e417
Revises: 
Create Date: 2026-07-30 16:11:07.608372
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '74f1ce54e417'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_handle_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_handle'), table_name='users')
    op.create_index(op.f('ix_users_handle'), 'users', ['handle'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_handle'), table_name='users')
    op.create_index(op.f('ix_users_handle'), 'users', ['handle'], unique=False)
    op.create_unique_constraint(op.f('users_handle_key'), 'users', ['handle'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
